# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4180f34
_src_path: copier_template
description: Testing bundling citation info with a python package
max_python: '3.13'
min_python: '3.10'
namespace_package: ''
nightly_deps: ''
orgname: jl-wynen
prettyname: TestSoftwareCitation
projectname: test_software_citation
related_projects: ''
year: 2024
